gesdinet_jwt_refresh_token:
  #single_use: true    #true para refrescar el token una sola vez
  ttl: 60              #tiempo de vida del refresh_token
  ttl_update: true    #para poder renovar el token en caso el refresh_token ya haya caducado